GRANT EVOLVE SCHEMA ON TABLE "DB_NAME"."SCHEMA_NAME"."TABLE_NAME" TO ROLE "ROLE_NAME";

ALTER TABLE "DB_NAME"."SCHEMA_NAME"."TABLE_NAME" SET ENABLE_SCHEMA_EVOLUTION = TRUE;

COPY INTO "DB_NAME"."SCHEMA_NAME"."TABLE_NAME"
FROM '@"DB_NAME"."SCHEMA_NAME"."STAGE_NAME"/your_file.csv'
FILE_FORMAT = (
    TYPE=CSV,
    SKIP_HEADER=0,
    FIELD_DELIMITER=',',
    TRIM_SPACE=FALSE,
    FIELD_OPTIONALLY_ENCLOSED_BY=NONE,
    DATE_FORMAT=AUTO,
    TIME_FORMAT=AUTO,
    TIMESTAMP_FORMAT=AUTO,
    ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE,
    PARSE_HEADER=TRUE
)
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
ON_ERROR=ABORT_STATEMENT;
